### PR TITLE
add link to edit page source on github (Wiki style)

### PR DESCRIPTION
**Pull request by hoijui**
(excerpt from PR https://github.com/LibreSolar/libresolar.github.io/pull/8)

### CODE REVIEW

**Comment by martinjaeger** [comment]
I'd like to integrate an edit link only if it fits well into the existing design. I can't check at the moment, but I guess the style is the same as in previous PR, correct?

**Comment by hoijui** [comment]
yes it's the same commit.
I just wanted to make a new commit to separate it from the other stuff.
this one could stay open until the style is fixed maybe.

**Comment by martinjaeger** [comment]
Good idea!

**Comment by martinjaeger** [comment]
Just finished a complete redesign of the website based on VuePress. An edit link is now present, so I'm closing this issue.

**Pull request closed without merging**
